server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100 # in query
    open-in-view: false
#    false이면 트랜잭션 종료시점에 DB 세션 종료 -> 트랜잭션 종료 후, LAZY LOADING 발동 불가
  output:
    ansi:
      enabled: always # vscode console color
#  프로필 사진 최대 크기 설정
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
logging:
  level:
    '[com.mino.blogproj]': DEBUG
    '[org.hibernate.type]': TRACE
    # 개발은 trace
    # trace -> debug -> info -> warn -> error
    # 개발시에만 TRACE

file:
  path: ./upload/
